name: "Ultra Disk Cleanup"
description: "Aggressively free disk space on GitHub Ubuntu runners for larger builds"
author: "khulnasoft-lab"
branding:
  icon: "hard-drive"
  color: "red"

inputs:
  debug:
    description: "Enable verbose debug logs"
    required: false
    default: "false"

outputs:
  saved-space:
    description: "Estimated disk space saved (in bytes)"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: bash "${{ github.action_path }}/cleanup.sh" "${{ inputs.debug }}"
