name: Test Cleanup

on: [push]

jobs:
  cleanup-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ultra Cleanup
        uses: ./ultra-disk-cleanup
        with:
          debug: true

      - name: Print saved space
        run: echo "Saved ${{ steps.cleanup.outputs.saved-space }} bytes"
